site_name: 'python-app'
site_description: 'Main documentation for Python App'
repo_url: https://github.com/raftriani/ApiPython

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'index.md'
